In [26]:
import numpy as np
import math

# High School Reunion Problem
With your high school reunion fast approaching, you decide to get in shape and lose some weight . You record your weight every day for five weeks starting on a Monday.
Given these daily weights, build an array with your average weight per weekend (Saturday and Sunday).

In [3]:
dailywts = 185 - np.arange(5*7)/5
print(dailywts)

[185.  184.8 184.6 184.4 184.2 184.  183.8 183.6 183.4 183.2 183.  182.8
 182.6 182.4 182.2 182.  181.8 181.6 181.4 181.2 181.  180.8 180.6 180.4
 180.2 180.  179.8 179.6 179.4 179.2 179.  178.8 178.6 178.4 178.2]


In [5]:
# Use slicing to get the weight for Saturday - 1st sat occurs at index 5, remaining in the array are 7 days later
sat = dailywts[5::7]
sun = dailywts[6::7]
average = (sat+sun)/2
print(average)

[183.9 182.5 181.1 179.7 178.3]


# Nola Problem
Make the following 4x7 array called nola that starts with 1 and steps by 2. However, note that the first element in each row is always 4 more than the last element in the previous row.

## Approach 1 (Mine)
Initialise the results array, create the individual arrays and insert it into the results using a for loop

In [12]:
# by default, it will create with floating point numbers which means there will be a trailing .0
# result = np.zeros(shape=(4,7))
result = np.zeros(shape=(4,7),dtype=int)
index = 0
start = 1
step = 2
for index in range(0,4):
    stop = start + 7 * step
    array = np.arange(start,stop,step)
    result[index] = array
    start = stop + 2
print(result)

[[ 1  3  5  7  9 11 13]
 [17 19 21 23 25 27 29]
 [33 35 37 39 41 43 45]
 [49 51 53 55 57 59 61]]


## Approach 2
The trick here is to think of nola as the first 7 columns in this 4x8 array where we can chop the last to get the (4x7) array
```
[[ 1  3  5  7  9 11 13 15]
 [17 19 21 23 25 27 2 319]
 [33 35 37 39 41 43  4745]
 [49 51 53 55 57 59 63 6
```
 `nola[:, :-1]` can be interpreted as "Select every row, and select all columns from the start, up to but excluding the last column". -1 means "last" index. See negative indexing1]]6

In [15]:
# build the sequence array
arr = np.arange(start=1,stop=65,step=2)
# reshape the 1D array into a 2D array
nola = np.reshape(arr,(4,8))
# delete the last element == select all the elements but the last
nola = nola[:, :-1]
print(nola)

[[ 1  3  5  7  9 11 13]
 [17 19 21 23 25 27 29]
 [33 35 37 39 41 43 45]
 [49 51 53 55 57 59 61]]


# Gold Miner Problem
After binge watching the discovery channel, you ditch your job as a trial lawyer to become a gold miner  . You decide to prospect five locations underneath a 7x7 grid of land. How much gold do you uncover at each location?
1. gold states how much gold is under each location in the 7x7 grid of land
2. 
locs states the coordinates of the five locations where you dig

In [19]:
import numpy as np

np.random.seed(5555)
gold = np.random.randint(low=0, high=10, size=(7,7))

print(gold)
# [[2 3 0 5 2 0 3]
#  [8 8 0 7 1 5 3]
#  [0 1 6 2 1 4 5]
#  [4 0 8 9 9 8 7]
#  [4 2 7 0 7 2 1]
#  [9 8 9 2 5 0 8]
#  [1 9 8 2 6 4 3]]

locs = np.array([
    [0,4],
    [2,2],
    [2,3],
    [5,1],
    [6,3]
])

# loop over every array in locs and get the value of gold and add it to the total
mined = 0
for location in locs:
    row = location[0]
    col = location[1]
    mined += gold[row][col]

print(mined)

[[2 3 0 5 2 0 3]
 [8 8 0 7 1 5 3]
 [0 1 6 2 1 4 5]
 [4 0 8 9 9 8 7]
 [4 2 7 0 7 2 1]
 [9 8 9 2 5 0 8]
 [1 9 8 2 6 4 3]]
20


# Roux Problem
Define a  roux array as a 1-D array such that, when it's reversed, it represents the sequence of square numbers 1, 4, 9, 16, ... with 0s interwoven between them. odd-length arrays begin with a square number while even-length arrays begin with a 0. Implement a function called make_roux(n) that inputs n, the desired size of the array, and outputs the corresponding roux array. Then test it on the examples above

In [30]:
# roux array of length 5 = [9 0 4 0 1]
# roux array of length 8 = [0 16  0  9  0  4  0  1]
# roux array of length 12 = [0 36  0 25  0 16  0  9  0  4  0  1]
def make_roux(n):
    roux = [] #initialise an array
    i = math.ceil(n/2)
    square_num = i * i
    while len(roux) < n:
        roux.append(square_num)
        if(len(roux)<n):
            roux.append(0) #append a 0 after appending the squared number all the time
        i-=1
        square_num = i*i
    if(n%2==0): # additional 0 to append for even numbers
        roux.insert(0,0)
        roux = roux[:n] # to check that roux has exactly n elements
    return roux

print(make_roux(5))
print(make_roux(8))
print(make_roux(12))

[9, 0, 4, 0, 1]
[0, 16, 0, 9, 0, 4, 0, 1]
[0, 36, 0, 25, 0, 16, 0, 9, 0, 4, 0, 1]


Source: https://www.practiceprobs.com/problemsets/python-numpy/beginner